version: "3"
services:
  es01:
    container_name: es01
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.0"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./data/es01:/usr/share/elasticsearch/data"
    healthcheck:
      test: [ "CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health" ]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: "docker.elastic.co/kibana/kibana:7.15.0"
    environment:
      ELASTICSEARCH_URL: "http://es01:9200"
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - es01

  logstash:
    container_name: logstash
    image: "docker.elastic.co/logstash/logstash-oss:7.15.0"
    volumes:
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    ports:
      - "9999:9999"
    networks:
      - elastic
    depends_on:
      - es01

networks:
  elastic:
    driver: bridge
